In [57]:
import pandas as pd
import numpy as np

In [58]:
mydata=pd.read_csv(r"C:\Users\student711\Desktop\pulkit\DataSets-master\DataSets-master\Data_MVLR.csv")

In [59]:
mydata.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [60]:
x_in=mydata.iloc[:,:4]
y_out=mydata.iloc[:,4]

In [61]:
y_out

0     541
1     524
2     561
3     414
4     410
5     457
6     344
7     467
8     464
9     498
10    580
11    471
12    525
13    508
14    566
15    635
16    603
17    714
18    865
19    640
20    649
21    540
22    464
23    547
24    460
25    566
26    577
27    631
28    574
29    534
30    571
31    554
32    577
33    628
34    487
35    644
36    640
37    704
38    648
39    968
40    587
41    699
42    632
43    591
44    782
45    510
46    610
47    524
Name: Petrol_Consumption, dtype: int64

In [62]:
from sklearn.model_selection import train_test_split

In [84]:
#split
x_train,x_test,y_train,y_test=train_test_split(x_in,y_out,test_size=.20,random_state=153)

In [85]:
#preprocessing
from sklearn.preprocessing import StandardScaler

In [86]:
myscaler=StandardScaler()

In [87]:
x_mystd=myscaler.fit_transform(x_train)
y_mystd=myscaler.fit_transform(y_train)
xx_test=myscaler.fit_transform(x_test)
yy_test=myscaler.fit_transform(y_test)

C:\Users\student711\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)
C:\Users\student711\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:586: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
C:\Users\student711\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:649: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
C:\Users\student711\Anacond

In [88]:
x_mystd

array([[  1.24997112e+00,  -1.01870975e-02,  -2.56689058e-01,
         -8.56460710e-01],
       [ -7.32453864e-01,  -9.73501571e-01,  -2.46114682e-01,
         -4.54016269e-01],
       [  2.24118362e+00,   1.92357751e+00,  -1.16581427e+00,
          8.84088475e-02],
       [ -2.36847617e-01,   1.08156931e+00,  -8.89795942e-01,
         -6.46489697e-01],
       [ -7.32453864e-01,   4.42927488e-01,   7.79328673e-01,
         -2.44045256e-01],
       [ -2.36847617e-01,  -7.45160363e-01,   9.29539043e-01,
          2.28389523e-01],
       [  7.54364877e-01,   5.53530261e-01,  -8.17130997e-01,
         -2.61542841e-01],
       [ -7.32453864e-01,   9.68478440e-02,   1.27632435e+00,
          3.50872614e-01],
       [ -7.32453864e-01,  -1.02950713e-01,   7.79599811e-01,
          1.05906432e-01],
       [ -7.32453864e-01,   6.47373616e-02,  -5.41654940e-01,
          6.48331548e-01],
       [  1.24997112e+00,   3.78706523e-01,  -4.58415620e-01,
          8.84088475e-02],
       [  2.58758630e

In [89]:
y_mystd

array([-0.26601797,  1.15140439, -1.02989828, -1.39486332, -0.68190836,
        0.44693699, -1.00443561,  0.48088723,  0.20928534,  0.45542455,
       -0.58005765, -0.32543088, -0.06231655, -0.97048537, -0.10475435,
       -0.46123183, -0.14719214, -0.91107246,  1.72855841,  1.0665288 ,
        3.30724439,  0.52332502, -0.0113912 ,  2.43302581,  0.59971305,
       -0.77527151,  0.59122549,  0.55727526, -1.98899246, -0.10475435,
        0.01407148,  0.10743463, -0.37635624, -0.94502269, -0.97048537,
       -0.31694332, -0.03685387, -0.20660506])

In [90]:
round(x_mystd.mean())

0.0

In [91]:
round(y_mystd.mean())

-0.0

In [92]:
round(y_mystd.std())

1.0

In [93]:
round(x_mystd.std())

1.0

In [94]:
from sklearn.linear_model import LinearRegression

In [95]:
myobj=LinearRegression()

In [96]:
mylearner=myobj.fit(x_mystd,y_mystd)

In [97]:
ya=yy_test

In [98]:
yp=mylearner.predict(xx_test)

In [99]:
from sklearn.metrics import mean_squared_error

In [100]:
error=mean_squared_error(ya,yp)

In [102]:
error=np.sqrt(error)

In [103]:
error

0.7115892995172326

In [105]:
mylearner.coef_

array([-0.31680673, -0.30077909, -0.10137643,  0.68319565])

In [106]:
mylearner.intercept_

-1.1372379718834081e-15